### ISSUE TITLE
ExDoc shortcut fails when non-ascii characters present in source file

### ISSUE THREAD

**Issue by sarevok-anchev** [slashmili/alchemist.vim#156]
If autocomplete/docs or etc doesn't work for you
before creating issue please check Debugging page and make sure your basic setup works

https://github.com/slashmili/alchemist.vim/wiki/Debugging

and answer these questions:

1. Elixir/OTP/Python version

Erlang/OTP 21 [erts-10.3.5.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.9.0 (compiled with Erlang/OTP 21)
Python 3.7.3

2. Are you using VIM or Neovim? Please provide the version.

VIM - Vi IMproved 8.1 

3. Which pluging are you using:

[X] basic omnifunc
[X] YouCompleteMe
[ ] deoplete

4. Which steps of Debugging passed?

[ ] Elixir Module definition
[ ] Elixir Function definition
[ ] Elixir Module/Function docs
[ ] Your Project Module definition
[ ] Your Project Function definition

5. Do you have a specific setup? Like Docker and etc

> Traceback (most recent call last):
 >  File "/home/user/.vim/bundle/alchemist.vim/after/../elixir_sense_client", line 81, in <module>
  >   main(sys.argv[1:])
  > File "/home/user/.vim/bundle/alchemist.vim/after/../elixir_sense_client", line 71, in main
   >  response = sense.process_command(request, source, line ,column)
  > File "/home/user/.vim/bundle/alchemist.vim/elixir_sense.py", line 54, in process_command
   >  req_erl_struct = erl_terms.encode(py_struct)
  > File "/home/user/.vim/bundle/alchemist.vim/erl_terms.py", line 212, in encode
  >   return b'\x83' + _encoder_func(struct)(struct)
 >  File "/home/user/.vim/bundle/alchemist.vim/erl_terms.py", line 241, in _encode_map
  >   b = b + _encoder_func(k)(k) +  _encoder_func(v)(v)
 >  File "/home/user/.vim/bundle/alchemist.vim/erl_terms.py", line 241, in _encode_map
  >   b = b + _encoder_func(k)(k) +  _encoder_func(v)(v)
  > File "/home/user/.vim/bundle/alchemist.vim/erl_terms.py", line 269, in _encode_string
 >    str_enc = obj.encode('utf-8')
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 204: ordinal not in range(128)

As the title says: having any non-ascii character makes looking up documentation via the shortcut (shift+k) fail with the above error.

**Comment by kenny-evitt** [comment]
The 'definition' commands fail for this too.

My (last error), for a 'show docs' command:

```
Traceback (most recent call last):
  File "/Users/kenny/.local/share/nvim/plugged/alchemist.vim/after/../elixir_sense_client", line 81, in <module>
    main(sys.argv[1:])
  File "/Users/kenny/.local/share/nvim/plugged/alchemist.vim/after/../elixir_sense_client", line 71, in main
    response = sense.process_command(request, source, line ,column)
  File "/Users/kenny/.local/share/nvim/plugged/alchemist.vim/elixir_sense.py", line 42, in process_command
    self._log('source: %s' % source)
  File "/Users/kenny/.local/share/nvim/plugged/alchemist.vim/elixir_sense.py", line 194, in _log
    f.write("%s\n" % text.encode('utf8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 27168: ordinal not in range(128)
```

**Comment by slashmili** [comment]
@kenny-evitt could what kind of character is in your docs? Does it happen only for one specific function or all functions?

**Comment by kenny-evitt** [comment]
@slashmili In my case it was either a `•` (bullet) or `·` (middle dot) character.

The error happened for all the functions – I think. I could only see the first line of what I'm guessing was the same error output for the 'definition' function.

**Comment by robsonpeixoto** [comment]
@slashmili the easier way to replicate this issue is reading the `Strings` documentation.  Try the `String.downcase` doc.

**Comment by slashmili** [comment]
Thanks @robsonpeixoto !

I created a PR, I'll try it today and if it doesn't break other commands, I'll merge it tonight

**Comment by slashmili** [comment]
The fix is pushed!

**Comment by kenny-evitt** [comment]
@slashmili I'm still getting this error for files with a `·` character in them:

```


E484: Can't open file: Traceback (most recent call last):
```
